### ISSUE TITLE
Crash on faulty options.ini

### ISSUE THREAD

**Issue by ulinvega** [RollingStar/GPack-Unofficial#1]
for some reason i can't decompress any of my GPack archive using this on Windows 10, i don't know the cause but maybe someone can help because i am stuck.

**Comment by ulinvega** [comment]
Sorry, the problem was in the options.ini file, something was changed and it caused it to crash every time i used it so i used the reset ini option "GPack --reset-ini" and now it works, maybe this will help someone else.

**Comment by RollingStar** [comment]
Cool! I also played around with converting this to x64, but never released anything. Since it's not my project, I think testing it would be a nightmare. However, replacing the 7zip binary with a 64 bit version seemed to work.
